### ISSUE TITLE
[Help] Failed to execute 'setEndAfter' on 'Range': the given Node has no parent.

### ISSUE THREAD

**Issue by djalmajr** [WebReflection/uland#3]
Hello! I'm studying uland for a small project, but I'm facing some problems...

When I use `html.for` for a list of todos, the following error happens (only on Chrome... Firefox works as expected):

![image](https://user-images.githubusercontent.com/1858147/89358695-708fc780-d69a-11ea-85e3-8f54617d0760.png)

with this piece of code:

```javascript
// src/containers/app.js
//...
<ul>
  ${filtered.map(todo => html.for(todo)`${Todo({ todo })}`)}
</ul>
//...
```

But, if I change to this:

```javascript
// src/containers/app.js
//...
<ul>
  ${filtered.map(todo => Todo({ todo })}}
</ul>
//...
```

The error goes away, but the benefits of use keyed list is lost.

I'm rerendering the app in this way:

```javascript
// src/index.js
//...
const wrapper = document.querySelector("#root");
const renderApp = () => render(wrapper, Component(App));

renderApp() && store.subscribe(renderApp);
```

P.S: checked attribute not work as expected in Chrome or Firefox (file `src/containers/todo.js`)

![image](https://user-images.githubusercontent.com/1858147/89359894-455aa780-d69d-11ea-9865-11b807090daa.png)

Link to the test project: https://codesandbox.io/embed/todo-uland-xy5rk?file=/src/index.js

**Comment by WebReflection** [comment]
Few things:
  * _uhtml_ handles keys automatically, but _uland_ always does the keying for you, there are really few reasons to use `html.for`, but if you have IDs, you better use it via `html.for(sameReference, todo.id)` or ... just don't bother with `html.for`, as it's not needed
  * `checked` is a boolean attribute, or a native accessor, with these kind of attributes, in _uhtml_, you want to use `.checked=${boolean}` instead of `checked=${boolean}` ... see [About Attributes](https://github.com/WebReflection/uhtml#api-documentation)
  * the project is quite articulated for a todo, but mostly I have zero time these days to review big projects ... try to keep it simple, see if after avoiding `html.for` and using `.checked` it works as meant, try to see if using _neverland_ instead works, as it's based in _lighterhtml_ which does something slightly different, but on top of this, if you think there is a bug, try to isolate the bug and show me the failing code, as going through dozen files is not helping me much

Thanks for collaborating and eventually helping me out to better help you out 👋

**Comment by WebReflection** [comment]
P.S. conditional renders, like in react, might cause issues too ... always return the same node from each component, and use eventually `aria-hidden=${true || false}` instead of returning an empty `html`, as that messes up completely the keyed logic, and also the eventual nested components logic ... 

```js
// TL;DR this is wrong
if (condition)
  return html``;
// ... because the key is on the node
return html`<div>a real node</div>`;
```

The following is better, and it's also cheaper, as there are less mutations on the DOM
```js
return html`<div aria-hidden="${hideCondition}">a real node</div>`;
// or ...
return html`<div .hidden="${hideCondition}">a real node</div>`;
// or
return html`<div class=${condition ? 'hidden' : ''}>a real node</div>`;
```

**Comment by djalmajr** [comment]
> P.S. conditional renders, like in react, might cause issues too ... always return the same node from each component, and use eventually `aria-hidden=${true || false}` instead of returning an empty `html`, as that messes up completely the keyed logic, and also the eventual nested components logic ...
> 
> ```js
> // TL;DR this is wrong
> if (condition)
>   return html``;
> // ... because the key is on the node
> return html`<div>a real node</div>`;
> ```
> 
> The following is better, and it's also cheaper, as there are less mutations on the DOM
> 
> ```js
> return html`<div aria-hidden="${hideCondition}">a real node</div>`;
> // or ...
> return html`<div .hidden="${hideCondition}">a real node</div>`;
> // or
> return html`<div class=${condition ? 'hidden' : ''}>a real node</div>`;
> ```

Awesome!

**Comment by djalmajr** [comment]
> Few things:
> 
> * _uhtml_ handles keys automatically, but _uland_ always does the keying for you, there are really few reasons to use `html.for`, but if you have IDs, you better use it via `html.for(sameReference, todo.id)` or ... just don't bother with `html.for`, as it's not needed
> * `checked` is a boolean attribute, or a native accessor, with these kind of attributes, in _uhtml_, you want to use `.checked=${boolean}` instead of `checked=${boolean}` ... see [About Attributes](https://github.com/WebReflection/uhtml#api-documentation)

I did these adjusts and the error goes away, however 😅 the following occurs:

![todo-keyed](https://user-images.githubusercontent.com/1858147/89431108-e2592700-d715-11ea-84e5-394267ce8506.gif)

The input content of active todo is filled with the content of completed todo... How I solve this without key?

> * the project is quite articulated for a todo, but mostly I have zero time these days to review big projects ... try to keep it simple, see if after avoiding `html.for` and using `.checked` it works as meant, try to see if using _neverland_ instead works, as it's based in _lighterhtml_ which does something slightly different, but on top of this, if you think there is a bug, try to isolate the bug and show me the failing code, as going through dozen files is not helping me much

I made this way to feel how would be in a more complex project :)

> 
> Thanks for collaborating and eventually helping me out to better help you out

Thank you for the quick response. I like the way you do some things and I would like to use uland (and µ-related) instead neverland for his tiny size.

**Comment by WebReflection** [comment]
if the input uses a `value`, then go `.value=${...}` instead ... same as `.checkbox`, these behaviors are defined by the DOM standard, `value` as attribute, instead of accessor, won't change the visible input content

**Comment by djalmajr** [comment]
> if the input uses a `value`, then go `.value=${...}` instead ... same as `.checkbox`, these behaviors are defined by the DOM standard, `value` as attribute, instead of accessor, won't change the visible input content

One single character did the thing 🎉🎉! Thanks again... I will try a more complex project.

**Comment by WebReflection** [comment]
@djalmajr if interested, I've explained in here why that's the case:
https://github.com/WebReflection/uhtml/issues/21#issuecomment-658678403
